# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 网易云飞升

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Script
        env:
          PHONE: ${{ secrets.PHONE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NOMD5_PASSWORD: ${{ secrets.NOMD5_PASSWORD }}
          PLAYLIST: ${{ secrets.PLAYLIST }}
          SCKEY: ${{ secrets.SCKEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          BARK_KEY: ${{ secrets.BARK_KEY }}
          WW_ID: ${{ secrets.WW_ID }}
          AGENT_ID: ${{ secrets.AGENT_ID }}
          APP_SECRETS: ${{ secrets.APP_SECRETS }}
        run: |
          if [ ${NOMD5_PASSWORD} ];then PASSWORD=$(echo -n "${NOMD5_PASSWORD}"|md5sum|cut -d " " -f1); fi
          if [ ${PLAYLIST} ];then PLAYLIST_CMD="-l $PLAYLIST"; fi
          if [ ${TG_BOT_TOKEN} ] && [ ${TG_CHAT_ID} ];then TG_PUSH_CMD="-c $TG_CHAT_ID -t $TG_BOT_TOKEN"; fi
          python3 action.py ${PHONE} ${PASSWORD} -s ${SCKEY} ${TG_PUSH_CMD} ${PLAYLIST_CMD} -b ${BARK_KEY} -w ${WW_ID} -e ${APP_SECRETS} -a ${AGENT_ID}
          
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 3
